def dvm_help():
    dvm_help_dict = {}
    dvm_help_dict['jobid']        = ''
    dvm_help_dict['unitscale']    = '! default 1.0, ABS(): for scale'                                                  
    dvm_help_dict['nbasis']       = '! no default'                                                                     
    dvm_help_dict['natom']        = ' ! no default'                                                                     
    dvm_help_dict['nsystem']      = '! no default'                                                                     
    dvm_help_dict['basisfile']    = '! default D53.DAT, atomic basis file'                                             
    dvm_help_dict['frozen']       = '! default 0, 0 all electron, /=0 frozen core'                                     
    dvm_help_dict['functional']   = '! default 0, ABS(): 0 barth-hedin, >0 kohn-sham'                                  
    dvm_help_dict['spin']         = '! defualt 0, 0 spin restrict, /=0 spin unrestrict'                                
    dvm_help_dict['charge']       = '! defualt 0.00, extra charge on whole system'                                     
    dvm_help_dict['ef']           = '! defualt 0.00, initial guessing value of ef'                                     
    dvm_help_dict['beta']         = '! default 4000.000, ABS(): beta in fermi function'                                
    dvm_help_dict['pftype']       = '! default 0, ABS(): partition function type'                                      
    dvm_help_dict['ipop']         = '! default 1, ABS(): 0 mulliken, 1 diagonal, >1 renormalized'                      
    dvm_help_dict['isolve']       = '! default 1, ABS(): 0 LU decomposition, >0 Lapack'                                
    dvm_help_dict['ifefld']       = '! default 0, ABS(): 0 no external E field, >0 yes'                                
    dvm_help_dict['efld']         = '! default 0.0 0.0 0.0, external E field'                                          
    dvm_help_dict['scfstep']      = ''
    dvm_help_dict['mixtype']      = '! default 0, ABS(): 0 old simple mixing, >0 Ellis simple mixing'                  
    dvm_help_dict['occshift']     = '! default 0.0002, for initializing the occupation number' 
    dvm_help_dict['ifscfdiis']    = '! defualt 1, ABS(): 0 no, 1 pulay, 2 broyden2, >2 broyden(wt.rms)'                
    dvm_help_dict['nscfdiis']     = '! defualt 6(at least 6), ABS(): number of SCF variational vectors'                
    dvm_help_dict['scfdiistol']   = '! defualt 0.05, ABS(): threshold from simple mixing to DIIS'                      
    dvm_help_dict['scfrhotol']    = '! default 0.00001, ABS(): charge density convergency criterion'                   
    dvm_help_dict['scfspntol']    = '! default 0.00001, ABS(): spin density convergency criterion'                     
    dvm_help_dict['scfrhomix']    = '! default 0.01, charge mixing, note <0 fixed for simple mixing'                   
    dvm_help_dict['scfspnmix']    = '! default 0.01, spin mixing, note <0 fixed for simple mixing'                     
    dvm_help_dict['grid3dseed']   = '! default 2 3 5, ABS(): irrational number seed'                                   
    dvm_help_dict['nbytediv']     = '! default 1000(at leat 600), ABS(): size(in MB) of basis function file'           
    dvm_help_dict['ifbsfn']       = '! no default, ABS(): 0 new basis function, 1 partly regenerate, >1 reload'        
    dvm_help_dict['smplmixload']  = '! no default, ABS(): 0 new variational param for simple mixing, >0 reload'        
    dvm_help_dict['ifetot']       = '! defualt 0, ABS(): 0 no total energy, 1 last 3 cycle, >1 each cycle'             
    dvm_help_dict['ifbypscfc']    = '! no default, ABS(): 0 do SCFC, >0 bypass'                                        
    dvm_help_dict['printbasis']   = '! default 0, ABS(): 0 brief, >0 different print level'                            
    dvm_help_dict['printscf']     = '! default 0, ABS(): 0 brief, >0 different print level'                            
    dvm_help_dict['ifpopu']       = '! default 0, ABS(): 0 no population output, >0 output'       
    dvm_help_dict['ifpdos']       = '! default 0, ABS(): 0 no pdos, >0 output pdos'                                    
    dvm_help_dict['nplot']        = '! defualt 0, <=0 no plot, >0(max 30) number of plot' 
    dvm_help_dict['plotinfo']     = '! default 111, ABS(): 0 nothing , 111 output char, diff, pot'                                   
    dvm_help_dict['ifdebug']      = '! defualt 0, ABS(): 0 nonstop, >0 stop after initialization'
    dvm_help_dict['frozeninfo']   = '! basis%nfrz  basis%nlsfrz'
    dvm_help_dict['grid3dinfo']   = '! basis%ngrid3d  basis%alpha  basis%r0'                      
    dvm_help_dict['plotgrid']     = '!     plot%dim, plot%ngrid'
    return dvm_help_dict 
